name: multipage
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  #sdk: ^3.5.0
  sdk: '>=3.4.0 <4.0.0'

  # version 3.24.0 ERROR REDIRECTION WEB downgrade 3.22.3
  # https://docs.flutter.dev/release/archive
  # >flutter downgrade 3.22.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  go_router: ^14.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
